### PR TITLE
Handle build name

### PR DESCRIPTION
**Pull request by pzpl**
I've added build name - full path displayed in popup is not clear, especially if You have several build scripts in same location. 
Also fixed default shortcut mapping on windows.

### CODE REVIEW

**Comment by vojtajina** [comment]
Why do you need this ?

I put build names, not paths into the "build_switcher_systems".

**Comment by pzpl** [comment]
It doesn't work when I put only build name ("Error trying to parse build system: No data in {BUILD_NAME}:1:1").

**Comment by vojtajina** [comment]
Smells like a windows issue :-D

Can you please rebase it on the latest master and change the README, to include example both with and without the path ?

Will merge it afterwards, thank you.

**Comment by pzpl** [comment]
I've merge latest master and update readme.

**Comment by shmup** [comment]
I experience the same problem on OS X. 

Error trying to parse build system: No data in Lua:1:1

**Comment by vojtajina** [comment]
Thank you!

**Pull request merged**
